version: '3'
services:
  database-local:
    image: "postgres"
    container_name: automation_db
    env_file:
      - database.env
    volumes:
      - dbdata:/var/lib/postgresql/data/
    ports:
    - 5432:5432
  api-local:
    build:
      context: ../
      dockerfile: ops/Dockerfile
    env_file:
      - api.env
    container_name: automation_api
    ports:
    - 5000:5000

volumes:
  dbdata:
networks:
  default:
    name: automation-network