# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.
on:
  release:
    types:
      - created

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Run build and test
        run: docker build -t knutfr/automation-github:api.${{ GITHUB_SHA }] -f ops/Dockerfile .

      - name: Build sidecar img for migration purpose
        run: docker build -t knutfr/automation-github:sidecar -f ops/Dockerfile.sidecar .

  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push API to Docker Hub
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: knutfr/automation-github:api.${{ GITHUB_REF }}
      - name: Push Sidecar to Docker Hub
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: knutfr/automation-github:sidecar.${{ GITHUB_REF }}
